---
- hosts: all
  become: true
  roles:
    - { role: apache2, tags: ['apache2', 'web', 'http', 'lemp'] }

    - { role: mysql, tags: ['mysql', 'mysql', 'db', 'lemp'] }

    - { role: php, tags: ['php', 'web', 'php-fpm', 'lemp'] }

    - { role: composer, tags: ['composer'] }
